POST http://localhost:8888/api/register
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

###
POST http://localhost:8888/api/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}
> {%
    client.global.set("jwt_token", response.body.token);
%}

### Good request
POST http://localhost:8888/api/feedback
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "note": "This is my feedback text",
  "rating": 4
}

### rating not in range
POST http://localhost:8888/api/feedback
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "note": "Im a bad request",
  "rating": 10
}
###note null should be allowed
POST http://localhost:8888/api/feedback
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
     "note": null,
  "rating": 5
}

### get all feedbacks
GET http://localhost:8888/api/feedback
Content-Type: application/json

### get 1 feedback
GET http://localhost:8888/api/feedback/2
Content-Type: application/json

### get non existant feedback
GET http://localhost:8888/api/feedback/100000
Content-Type: application/json